apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.97.62.196:8080"
  restauthenabled: "true"
  restuser: "admin"
  restuserkey: "heketi-admin"
