---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kanali
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: kanali
  template:
    metadata:
      labels:
        k8s-app: kanali
    spec:
      serviceAccountName: kanali
      containers:
      - name: kanali
        imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
        image: {{.Values.imageRegistry}}/kanali:{{.Values.dockerImageTag}}
        command:
        - /kanali
        - start
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: pki
          mountPath: /etc/pki
        - name: config
          mountPath: /etc/kanali
      volumes:
      - name: pki
        projected:
          sources:
          - secret:
              name: {{.Values.tlsSecretName}}
              items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
          - secret:
              name: {{.Values.decryptKeySecretName}}
              items:
              - key: key.pem
                path: key.pem
      - name: config
        configMap:
          name: {{.Values.kanaliConfigName}}