---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kanali
  namespace: default
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: kanali
  targetCPUUtilizationPercentage: 500