# ---
#
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: jaeger-agent
#   namespace: tracing
# spec:
#   replicas: 1
#   selector:
#     name: jaeger-agent
#   strategy:
#     type: Recreate
#   selector:
#     matchLabels:
#       name: jaeger-agent
#   template:
#     metadata:
#       labels:
#         name: jaeger-agent
#         jaeger-infra: agent
#     spec:
#       containers:
#       - name: agent
#         image: registry.nmlv.nml.com/epitropos/jaegertracing/jaeger-agent:latest
#         command:
#         - /go/bin/agent-linux
#         args:
#         - -collector.host-port=jaeger-collector.tracing.svc.cluster.local:14267
#         - -discovery.min-peers=3
#         - -http-server.host-port=:5778
#         - -processor.jaeger-binary.server-host-port=:6832
#         - -processor.jaeger-binary.server-max-packet-size=65000
#         - -processor.jaeger-binary.server-queue-size=1000
#         - -processor.jaeger-binary.workers=10
#         - -processor.jaeger-compact.server-host-port=:6831
#         - -processor.jaeger-compact.server-max-packet-size=65000
#         - -processor.jaeger-compact.server-queue-size=1000
#         - -processor.jaeger-compact.workers=10
#         - -processor.zipkin-compact.server-host-port=:5775
#         - -processor.zipkin-compact.server-max-packet-size=65000
#         - -processor.zipkin-compact.server-queue-size=1000
#         - -processor.zipkin-compact.workers=10
#         ports:
#         - containerPort: 5775
#           protocol: UDP
#         - containerPort: 6831
#           protocol: UDP
#         - containerPort: 6832
#           protocol: UDP
#         - containerPort: 5778
#           protocol: TCP
#         resources: {}
#         imagePullPolicy: Always
#       securityContext: {}
#
# ---
#
# apiVersion: v1
# kind: Service
# metadata:
#   name: jaeger-agent
#   namespace: tracing
#   labels:
#     jaeger-infra: agent
# spec:
#   ports:
#   - name: agent-zipkin-thrift
#     port: 5775
#     protocol: UDP
#     targetPort: 5775
#   - name: agent-compact
#     port: 6831
#     protocol: UDP
#     targetPort: 6831
#   - name: agent-binary
#     port: 6832
#     protocol: UDP
#     targetPort: 6832
#   - name: agent-sampling
#     port: 5778
#     protocol: TCP
#     targetPort: 5778
#   selector:
#     name: jaeger-agent
#   type: ClusterIP
