# ---
#
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: jaeger-cassandra
#   namespace: tracing
# spec:
#   replicas: 1
#   selector:
#     name: jaeger-cassandra
#   selector:
#     matchLabels:
#       name: jaeger-cassandra
#   template:
#     metadata:
#       labels:
#         name: jaeger-cassandra
#     spec:
#       containers:
#       - name: cassandra
#         image: registry.nmlv.nml.com/epitropos/jaegertracing/cassandra:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 9042
#           protocol: TCP
#       - name: status
#         image: registry.nmlv.nml.com/epitropos/jaegertracing/cassandra-status:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8080
#           protocol: TCP
#
# ---
#
# apiVersion: v1
# kind: Service
# metadata:
#   name: jaeger-cassandra
#   namespace: tracing
# spec:
#   ports:
#   - name: cassandra-port
#     port: 9042
#     protocol: TCP
#     targetPort: 9042
#   - name: health-port
#     port: 8080
#     protocol: TCP
#     targetPort: 8080
#   selector:
#     name: jaeger-cassandra
#   type: ClusterIP
