# ---
#
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: jaeger
#   namespace: tracing
# spec:
#   replicas: 1
#   selector:
#     name: jaeger
#   strategy:
#     type: Recreate
#   selector:
#     matchLabels:
#       name: jaeger
#   template:
#     metadata:
#       labels:
#         name: jaeger
#         jaeger-infra: all
#     spec:
#       containers:
#       - name: jaeger-collector
#         image: registry.nmlv.nml.com/epitropos/jaegertracing/jaeger-collector:latest
#         command:
#         - /go/bin/collector-linux
#         args:
#         - -cassandra.connections-per-host=2
#         - -cassandra.keyspace=jaeger_v1_local
#         - -cassandra.max-retry-attempts=3
#         - -cassandra.port=9042
#         - -cassandra.proto-version=4
#         - -cassandra.servers=127.0.0.1
#         - -cassandra.socket-keep-alive=0h0m0s
#         - -cassandra.timeout=0h1m0s
#         - -collector.http-port=14268
#         - -collector.num-workers=50
#         - -collector.port=14267
#         - -collector.queue-size=2000
#         - -collector.write-cache-ttl=12h0m0s
#         - -dependency-storage.data-frequency=24h0m0s
#         - -dependency-storage.type=cassandra
#         - -log-level=info
#         - -runtime-metrics-frequency=0h0m1s
#         - -span-storage.type=cassandra
#         ports:
#         - containerPort: 14267
#           protocol: UDP
#         - containerPort: 14268
#           protocol: TCP
#         readinessProbe:
#           httpGet:
#             path: /readiness
#             port: 8080
#           initialDelaySeconds: 30
#           periodSeconds: 10
#         imagePullPolicy: Always
#       - name: jaeger-query
#         image: jaegertracing/jaeger-query:latest
#         imagePullPolicy: Always
#         command:
#         - /go/bin/query-linux
#         args:
#         - -cassandra.connections-per-host=2
#         - -cassandra.keyspace=jaeger_v1_local
#         - -cassandra.max-retry-attempts=3
#         - -cassandra.port=9042
#         - -cassandra.proto-version=4
#         - -cassandra.servers=127.0.0.1
#         - -cassandra.socket-keep-alive=0h0m0s
#         - -cassandra.timeout=0h1m0s
#         - -dependency-storage.data-frequency=24h0m0s
#         - -dependency-storage.type=cassandra
#         - -log-level=info
#         - -query.port=16686
#         - -query.prefix=api
#         - -query.static-files=jaeger-ui-build/build/
#         - -runtime-metrics-frequency=0h0m1s
#         - -span-storage.type=cassandra
#         readinessProbe:
#           httpGet:
#             path: /readiness
#             port: 8080
#           initialDelaySeconds: 30
#           periodSeconds: 10
#         ports:
#         - containerPort: 16686
#           protocol: TCP
#         readinessProbe:
#           httpGet:
#             path: /
#             port: 16686
#           initialDelaySeconds: 5
#       - name: jaeger-agent
#         image: jaegertracing/jaeger-agent:latest
#         imagePullPolicy: Always
#         command:
#         - /go/bin/agent-linux
#         args:
#         - -collector.host-port=127.0.0.1:14267
#         - -discovery.min-peers=3
#         - -http-server.host-port=:5778
#         - -processor.jaeger-binary.server-host-port=:6832
#         - -processor.jaeger-binary.server-max-packet-size=65000
#         - -processor.jaeger-binary.server-queue-size=1000
#         - -processor.jaeger-binary.workers=10
#         - -processor.jaeger-compact.server-host-port=:6831
#         - -processor.jaeger-compact.server-max-packet-size=65000
#         - -processor.jaeger-compact.server-queue-size=1000
#         - -processor.jaeger-compact.workers=10
#         - -processor.zipkin-compact.server-host-port=:5775
#         - -processor.zipkin-compact.server-max-packet-size=65000
#         - -processor.zipkin-compact.server-queue-size=1000
#         - -processor.zipkin-compact.workers=10
#         readinessProbe:
#           httpGet:
#             path: /readiness
#             port: 8080
#           initialDelaySeconds: 30
#           periodSeconds: 10
#         ports:
#         - containerPort: 5775
#           protocol: UDP
#         - containerPort: 6831
#           protocol: UDP
#         - containerPort: 6832
#           protocol: UDP
#         - containerPort: 5778
#           protocol: TCP
#       - name: cassandra
#         image: registry.nmlv.nml.com/epitropos/jaegertracing/cassandra:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 9042
#           protocol: TCP
#       - name: cassandra-status
#         image: registry.nmlv.nml.com/epitropos/jaegertracing/cassandra-status:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 8080
#           protocol: TCP
#
# ---
#
# apiVersion: v1
# kind: Service
# metadata:
#   name: jaeger-query
#   namespace: tracing
#   labels:
#     jaeger-infra: query
# spec:
#   ports:
#   - name: query-http
#     port: 80
#     protocol: TCP
#     targetPort: 16686
#   selector:
#     name: jaeger
#   type: NodePort
#
# ---
#
# apiVersion: v1
# kind: Service
# metadata:
#   name: jaeger-agent
#   namespace: tracing
#   labels:
#     jaeger-infra: agent
# spec:
#   ports:
#   - name: agent-zipkin-thrift
#     port: 5775
#     protocol: UDP
#     targetPort: 5775
#   - name: agent-compact
#     port: 6831
#     protocol: UDP
#     targetPort: 6831
#   - name: agent-binary
#     port: 6832
#     protocol: UDP
#     targetPort: 6832
#   selector:
#     name: jaeger
#   type: ClusterIP
